# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Remon Albear
title: Biomedical and Softawre enginnering student
email: remonalbear522@gmail.com
# phone: 01121963376
# website: Your websit

# Social links
# twitter_username: jekyllrb
github_username: remonalbear
# dribbble_username: jekyll
facebook_username: remon.alber
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: remon-albear-496b05155/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
about_title: About Me  #(Use this to override about section title)
about_profile_image: ./assets/remon.jpg
about_content: | # this will include new lines to allow paragraphs
 Hello,I'm Remon Albear,I'm <mark>biomedical</mark> enginnering student at Cairo university.I'm interested
 in <mark>software</mark> field especially in web development, embedded systems and machine learning.
 I'm a self learner i like to learn more about every thing and i will continue learning.
 I'm also working in the printing industry (digital and offset printing) and i have experiance in this field more than 8 years.

#Education Section
#Education: Education and Training  #(Use this to override about education section title)
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)



# More Section
more_title: Skills and Interests #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
 <h1>Skills</h1> 
  - <h2> Software </h2> 
   - Web development: html ,css ,javascript ,Reactjs, Nodejs ,Flask
   - Embedded systems: C programming language , AVR
   - C++ programming language
   - OOP
   - Data structure and algorithms
   - Machine learning
   - Python programming language 
   - R programming language 
   - Arduino 
  - <h2>Photo Editing</h2>
   - PhotoShop  
  - <h2>Microsoft office</h2>
   - Word
   - Power point
  - <h2>Languages</h2>
   - Arabic (native language)
   - English (very good)
   - French (fair)
   - Germany (fair)

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
